FROM rocker/verse
RUN R -e "install.packages(\"tidyverse\")"
RUN R -e "install.packages(\"readxl\")"
RUN R -e "install.packages(\"qtl\")" 
RUN R -e "install.packages(\"MASS\")" 
RUN R -e "install.packages(\"MESS\")"
RUN R -e "install.packages(\"lme4\")"
RUN R -e "install.packages(\"knitr\")"
RUN R -e "install.packages(\"tinytex\")" 
RUN R -e "library(\"tinytex\"); tinytex::install_tinytex(dir=\"/opt/tinytex\")"
RUN R -e "install.packages(\"Rcpp\")" 